Some minor cleanup in test/

diff --git a/test/r2-v b/test/r2-v
--- a/test/r2-v
+++ b/test/r2-v
@@ -1,18 +1,17 @@
 #!/bin/sh
-if test -z "${R2_MASTER}"; then
-	R2_MASTER=~/radare2/
-fi
+
+[ -z "${R2_MASTER}" ] && R2_MASTER="${PWD}/.."
 COPIES=~/prg/r2-v
 
-if  ! test -d "${R2_MASTER}"; then
+if ! test -d "${R2_MASTER}"; then
 	echo "Cannot find master copy of r2 at R2_MASTER=${R2_MASTER}"
 	exit 1
 fi
 
 
 if ! mkdir -p "${COPIES}"; then
-   echo "Cannot create COPIES=${COPIES}"
-   exit 1
+	echo "Cannot create COPIES=${COPIES}"
+	exit 1
 fi
 
 echo "Using R2_MASTER ${R2_MASTER}"
@@ -20,17 +19,17 @@ echo "Using COPIES ${COPIES}"
 
 
 Fail() {
- printf "%s" "$1\n"
- exit 1 
+	printf "%s" "$1\n"
+	exit 1
 }
 
 Head() {
-	cd ${R2_MASTER}   || Fail "cannot chdir to ${R2_MASTER}" 
+	cd ${R2_MASTER}   || Fail "cannot chdir to ${R2_MASTER}"
 	git rev-list HEAD |  head -n1
 }
 
 Next() {
-	cd ${R2_MASTER}   || Fail "cannot chdir to ${R2_MASTER}" 
+	cd ${R2_MASTER}   || Fail "cannot chdir to ${R2_MASTER}"
 	git rev-list HEAD | grep -C 1 $1 |head -n1
 }
 
@@ -88,7 +87,7 @@ init)
 	Clone `Head`
 	;;
 log)
-	cd ${R2_MASTER} || Fail "cannot chdir to ${R2_MASTER}" 
+	cd ${R2_MASTER} || Fail "cannot chdir to ${R2_MASTER}"
 	cur=`Cur`
 	for a in `git rev-list HEAD` ; do
 		NOTE=`cat ${COPIES}/radare2-${a}.note 2>/dev/null`
@@ -147,7 +146,7 @@ note)
 	Note $2 $3
 	;;
 diff)
-	cd ${R2_MASTER} || Fail "cannot chdir to ${R2_MASTER}" 
+	cd ${R2_MASTER} || Fail "cannot chdir to ${R2_MASTER}"
 	git diff `Cur`^..`Cur`
 	;;
 use)
