Update configure with acr-1.9.4 (adds --quiet) ##build

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.9.3
+# This script was automatically generated by ACR v1.9.4
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -58,6 +58,11 @@ eval "$1_OS=\"$SPLIT_OS\""
 shift
 [ -z "$1" ] && break
 done
+}
+
+QUIET=0
+be_quiet() {
+	QUIET=1
 }
 
 VPATH=`dirname ${0}`
@@ -141,6 +146,7 @@ Defaults for the options are specified in brackets.
 Configuration:
   -h, --help              display this help and exit
   -r, --report            show what libs/programs require to work
+  -q, --quiet             be less verbose
   -V, --version           display version information and exit
 
 Installation directories:
@@ -169,7 +175,8 @@ System types:
   --target=TARGET        configure for building compilers for TARGET [HOST]
 EOF2
 
-printf "\nOptional Features:
+printf "
+Optional Features:
   --disable-debugger     disable native debugger features
   --with-sysmagic        force to use system's magic
   --with-capstone5       build next branch of the capstone repository
@@ -190,8 +197,10 @@ printf "\nOptional Features:
   --with-libversion      specify different libversion (LIBVERSION=xxx)
   --without-jemalloc     build without jemalloc
   --without-r2r          build without r2r for regression testing
-  --with-checks-level    value between 0 and 3 to enable different level of assert (see R_CHECKS_LEVEL) (R_CHECKS_LEVEL=2)\n"
-printf "\nSome influential environment variables:
+  --with-checks-level    value between 0 and 3 to enable different level of assert (see R_CHECKS_LEVEL) (R_CHECKS_LEVEL=2)
+"
+printf "
+Some influential environment variables:
   CC          C compiler command
   CFLAGS      C compiler flags
   CPPFLAGS    C preprocessor flags
@@ -199,8 +208,10 @@ printf "\nSome influential environment variables:
               nonstandard directory <lib dir>
   CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
               headers in a nonstandard directory <include dir>
-  CPP         C preprocessor\n"
-printf "\nReport bugs to: pancake <pancake@nopcode.org>"
+  CPP         C preprocessor
+"
+printf "
+Report bugs to: pancake <pancake@nopcode.org>"
 echo ""
 exit 0
 }
@@ -212,8 +223,22 @@ take_environ() {
 : ${PREFIX:=/usr/local/}
 }
 
+ochof() {
+	[ "$QUIET" = 1 ] && return
+	printf "$*"
+}
+
+ocho() {
+	[ "$QUIET" = 1 ] && return
+	echo "$*"
+}
+
 show_version() {
-echo "radare2-4.6.0-git configuration script done with acr v1.9.3.
+if [ "$QUIET" = 1 ]; then
+	echo "4.6.0-git"
+	exit 0
+fi
+echo "radare2-4.6.0-git configuration script done with acr v1.9.4.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -233,6 +258,11 @@ fi
 case $flag in
 -h|--help|--hel|--h|--he|-help)
 	show_usage ; ;;
+-qV|-quiet-version|--quiet-version)
+	be_quiet
+	show_version ; ;;
+-q|-quiet|--quiet)
+	be_quiet ; ;;
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
@@ -330,15 +360,15 @@ ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCD
 
 create_environ
 
-echo "checking build system type... ${BUILD}"
-echo "checking host system type... ${HOST}"
-echo "checking target system type... ${TARGET}"
+ocho "checking build system type... ${BUILD}"
+ocho "checking host system type... ${HOST}"
+ocho "checking target system type... ${TARGET}"
 [ "${CROSSBUILD}" = 1 ] && echo "using crosscompilation mode."
 
 #split_host BUILD HOST TARGET
 [ -n "${prefix}" ] && PREFIX="${prefix}"
-echo "checking for working directories... ${WODIS}"
-echo "using prefix '${PREFIX}'"
+ocho "checking for working directories... ${WODIS}"
+ocho "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe"
 
 
@@ -371,7 +401,7 @@ else
 	DL_LIBS=""
 	echo "libc"
 fi
-printf "checking for patch... "
+ochof "checking for patch... "
 if [ -x "${PATCH}" ]; then
 	FIND=${PATCH}
 else
@@ -386,16 +416,20 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_PATCH=1
 	PATCH=${FIND}
 else
 	HAVE_PATCH=0
 	PATCH=patch
+if [ "" = 1 ]; then
+echo "Cannot find patch" >&2
+else
 echo no
+fi
 	echo "error: This program is required." >&2
 	exit 1 ; fi
-printf "checking for git... "
+ochof "checking for git... "
 if [ -x "${GIT}" ]; then
 	FIND=${GIT}
 else
@@ -410,13 +444,17 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_GIT=1
 	GIT=${FIND}
 else
 	HAVE_GIT=0
 	GIT=git
-echo no ; fi
+if [ "" = 1 ]; then
+echo "Cannot find git" >&2
+else
+echo no
+fi ; fi
 check_library() {
 VAR=$1
 S="$"
@@ -716,7 +754,7 @@ if [ -f "${VPATH}/${A}.acr" ]; then
    exit 1
   fi
  fi
- echo "creating ${SD_TARGET}"
+ ocho "creating ${SD_TARGET}"
 mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
  cat ${VPATH}/${SD_TARGET}.acr | \
 eval sed -e "s,@VPATH@,${VPATH}/${A},g" ${SEDFLAGS} > ${SD_TARGET}.tmp
@@ -736,10 +774,12 @@ done
 done
 
 do_remove
+if [ "$QUIET" = 0 ]; then
 echo
 echo "Final report:"
-for A in  R_CHECKS_LEVEL WANT_R2R PREFIX HAVE_LIB_GMP HAVE_OPENSSL HAVE_LIBUV USE_CAPSTONE HAVE_PTRACE USE_PTRACE_WRAP HAVE_FORK VERSION USE_LIB_ZIP USE_LIB_MAGIC USE_LIB_XXHASH DEBUGGER CC USERCC HAVE_ARC4RANDOM_UNIFORM HAVE_EXPLICIT_BZERO HAVE_EXPLICIT_MEMSET WANT_DYLINK USEROSTYPE LIBVERSION BUILD HOST TARGET ; do # REPORT
+for A in  R_CHECKS_LEVEL WANT_R2R PREFIX HAVE_LIB_GMP HAVE_OPENSSL HAVE_LIBUV USE_CAPSTONE HAVE_PTRACE USE_PTRACE_WRAP HAVE_FORK VERSION USE_LIB_ZIP USE_LIB_MAGIC USE_LIB_XXHASH DEBUGGER CC USERCC HAVE_ARC4RANDOM_UNIFORM HAVE_EXPLICIT_BZERO HAVE_EXPLICIT_MEMSET WANT_DYLINK USEROSTYPE LIBVERSION BUILD HOST TARGET ; do
 eval VAL="\$${A}"
 [ -z "${VAL}" ] && VAL="(null)"
 echo " - ${A} = ${VAL}"
 done
+fi
