Detect system Zydis without pkg-config ##arch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -443,7 +443,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR DESCRIPTION INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGCFG_LIBDIR PKGCFG_INCDIR PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C DEBUGGER HAVE_LIB_DL DL_LIBS PKGCONFIG R2_BUILDSYSTEM HAVE_PATCH PATCH HAVE_AR AR HAVE_GIT GIT HAVE_GPERF GPERF HAVE_LIB_ATOMIC HAVE_LIB_MAGIC HAVE_LINUX_CAN_H USE_LIB_ATOMIC LIBATOMIC USE_MAGIC USE_LIB_MAGIC LIBMAGIC WANT_THREADS LOADLIBS R_CRITICAL_ENABLED WANT_QJS WANT_DYLINK HAVE_FORK WANT_PTRACE_WRAP WANT_GPERF WANT_CAPSTONE WANT_ZYDIS WITH_LIBR WITH_STATIC_THEMES USE_CSNEXT USE_CS5 USE_CS4 WITH_CAPSTONE WITHOUT_SYSCAPSTONE CAPSTONE_CFLAGS CAPSTONE_LDFLAGS HAVE_PKGCFG_CAPSTONE USE_CAPSTONE WITH_ZYDIS WITHOUT_SYSZYDIS ZYDIS_CFLAGS ZYDIS_LDFLAGS HAVE_PKGCFG_ZYDIS USE_ZYDIS USE_SYS_ZYDIS SQSH_CFLAGS SQSH_LDFLAGS HAVE_PKGCFG_LIBSQSH WITH_SQSH USE_SQSH LZ4_CFLAGS LZ4_LDFLAGS HAVE_PKGCFG_LIBLZ4 WITH_SYSLZ4 USE_SYSLZ4 WANT_ZIP HAVE_LIB_Z HAVE_LIB_ZIP USE_ZIP USE_LIB_ZIP LIBZIP PKGCFG_ZLIBS PKGCFG_LIBZIPLIBS PKGCFG_R_ARCH_LIBS_PRIVATE PKGCFG_R_ASM_LIBS_PRIVATE PKGCFG_R_BIN_LIBS_PRIVATE PKGCFG_R_DEBUG_LIBS_PRIVATE PKGCFG_R_FS_LIBS_PRIVATE PKGCFG_R_IO_LIBS_PRIVATE PKGCFG_R_LANG_LIBS_PRIVATE PKGCFG_R_UTIL_LIBS_PRIVATE HAVE_LIB_XXHASH USE_XXHASH USE_LIB_XXHASH LIBXXHASH WITH_GPL HAVE_DECL_ADDR_NO_RANDOMIZE HAVE_DECL___GLIBC__ HAVE_ARC4RANDOM_UNIFORM HAVE_EXPLICIT_BZERO HAVE_EXPLICIT_MEMSET HAVE_CLOCK_NANOSLEEP HAVE___ATOMIC_FETCH_ADD_8 HAVE_SIGACTION HAVE_CLOCK_GETTIME FORCE_LIB_ATOMIC CLOCK_LDFLAGS SUPPORT_GNU99 HAVE_LIB_GMP WANT_SSL WANT_SSL_CRYPTO HAVE_OPENSSL SSL_CFLAGS SSL_LDFLAGS HAVE_LIB_SSL HAVE_PKGCFG_OPENSSL WANT_LIBUV HAVE_LIBUV_VERSION_1_0_0 LIBUV_CFLAGS LIBUV_LDFLAGS HAVE_PKGCFG_LIBUV HAVE_LIBUV WANT_V35 R2_WASM_BROWSER USE_RPATH USE_BUNDLE_PREFIX USERCC USEROSTYPE LIBVERSION HAVE_JEMALLOC HAVE_PTRACE USE_PTRACE_WRAP R_CHECKS_LEVEL WANT_DEBUGSTUFF"
+ENVWORDS="MANDIR DESCRIPTION INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGCFG_LIBDIR PKGCFG_INCDIR PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C DEBUGGER HAVE_LIB_DL DL_LIBS PKGCONFIG R2_BUILDSYSTEM HAVE_PATCH PATCH HAVE_AR AR HAVE_GIT GIT HAVE_GPERF GPERF HAVE_LIB_ATOMIC HAVE_LIB_MAGIC HAVE_LINUX_CAN_H USE_LIB_ATOMIC LIBATOMIC USE_MAGIC USE_LIB_MAGIC LIBMAGIC WANT_THREADS LOADLIBS R_CRITICAL_ENABLED WANT_QJS WANT_DYLINK HAVE_FORK WANT_PTRACE_WRAP WANT_GPERF WANT_CAPSTONE WANT_ZYDIS WITH_LIBR WITH_STATIC_THEMES USE_CSNEXT USE_CS5 USE_CS4 WITH_CAPSTONE WITHOUT_SYSCAPSTONE CAPSTONE_CFLAGS CAPSTONE_LDFLAGS HAVE_PKGCFG_CAPSTONE USE_CAPSTONE WITH_ZYDIS WITHOUT_SYSZYDIS WANT_SYS_ZYDIS ZYDIS_CFLAGS ZYDIS_LDFLAGS HAVE_PKGCFG_ZYDIS HAVE_SYS_ZYDIS USE_ZYDIS USE_SYS_ZYDIS SQSH_CFLAGS SQSH_LDFLAGS HAVE_PKGCFG_LIBSQSH WITH_SQSH USE_SQSH LZ4_CFLAGS LZ4_LDFLAGS HAVE_PKGCFG_LIBLZ4 WITH_SYSLZ4 USE_SYSLZ4 WANT_ZIP HAVE_LIB_Z HAVE_LIB_ZIP USE_ZIP USE_LIB_ZIP LIBZIP PKGCFG_ZLIBS PKGCFG_LIBZIPLIBS PKGCFG_R_ARCH_LIBS_PRIVATE PKGCFG_R_ASM_LIBS_PRIVATE PKGCFG_R_BIN_LIBS_PRIVATE PKGCFG_R_DEBUG_LIBS_PRIVATE PKGCFG_R_FS_LIBS_PRIVATE PKGCFG_R_IO_LIBS_PRIVATE PKGCFG_R_LANG_LIBS_PRIVATE PKGCFG_R_UTIL_LIBS_PRIVATE HAVE_LIB_XXHASH USE_XXHASH USE_LIB_XXHASH LIBXXHASH WITH_GPL HAVE_DECL_ADDR_NO_RANDOMIZE HAVE_DECL___GLIBC__ HAVE_ARC4RANDOM_UNIFORM HAVE_EXPLICIT_BZERO HAVE_EXPLICIT_MEMSET HAVE_CLOCK_NANOSLEEP HAVE___ATOMIC_FETCH_ADD_8 HAVE_SIGACTION HAVE_CLOCK_GETTIME FORCE_LIB_ATOMIC CLOCK_LDFLAGS SUPPORT_GNU99 HAVE_LIB_GMP WANT_SSL WANT_SSL_CRYPTO HAVE_OPENSSL SSL_CFLAGS SSL_LDFLAGS HAVE_LIB_SSL HAVE_PKGCFG_OPENSSL WANT_LIBUV HAVE_LIBUV_VERSION_1_0_0 LIBUV_CFLAGS LIBUV_LDFLAGS HAVE_PKGCFG_LIBUV HAVE_LIBUV WANT_V35 R2_WASM_BROWSER USE_RPATH USE_BUNDLE_PREFIX USERCC USEROSTYPE LIBVERSION HAVE_JEMALLOC HAVE_PTRACE USE_PTRACE_WRAP R_CHECKS_LEVEL WANT_DEBUGSTUFF"
 
 create_environ
 
@@ -716,6 +716,10 @@ USE_CAPSTONE="0"
 HAVE_PKGCFG_CAPSTONE="0"
 CAPSTONE_CFLAGS=""
 CAPSTONE_LDFLAGS=""; fi
+WANT_SYS_ZYDIS="0"
+if [ 11 = "$WITH_ZYDIS$WANT_ZYDIS" ]; then
+
+WANT_SYS_ZYDIS="1"; fi
 if [ "$WITH_ZYDIS" = "1" ]; then
 if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
 printf 'checking pkg-config flags for zydis... '
@@ -727,14 +731,28 @@ ZYDIS_CFLAGS=$tmp;
 tmp=`${PKGCONFIG} --libs zydis 2>/dev/null`
 if [ $? = 0 ]; then
 echo yes; HAVE_PKGCFG_ZYDIS=1;
-ZYDIS_LDFLAGS=$tmp; fi; fi; fi
+ZYDIS_LDFLAGS=$tmp; fi; fi
+ochof "checking for HAVE_SYS_ZYDIS... "
+ if [ -z "${ZYDIS_LDFLAGS}" ]; then ZYDIS_LDFLAGS="-lzydis"; fi ; echo '#include <Zydis/Zydis.h>' > .test.c ; echo 'int main(void) { return ZydisGetVersion() == 0; }' >> .test.c ; eval ${CC} ${CFLAGS} ${CPPFLAGS} ${ZYDIS_CFLAGS} .test.c ${LDFLAGS} ${ZYDIS_LDFLAGS} -o .test >/dev/null 2>&1 ; HAVE_SYS_ZYDIS=$? ; rm -f .test.c .test
+if [ "$HAVE_SYS_ZYDIS" = 0 ]; then
+	HAVE_SYS_ZYDIS=1
+	echo yes
+else
+	HAVE_SYS_ZYDIS=0
+	echo no
+fi; fi
 if [ 11 = "$WITH_ZYDIS$HAVE_PKGCFG_ZYDIS" ]; then
 
 USE_ZYDIS="1"
 USE_SYS_ZYDIS="1"
 else
+if [ 11 = "$WITH_ZYDIS$HAVE_SYS_ZYDIS" ]; then
+
+USE_ZYDIS="1"
+USE_SYS_ZYDIS="1"
+else
 USE_ZYDIS="0"
-USE_SYS_ZYDIS="0"; fi
+USE_SYS_ZYDIS="0"; fi; fi
 if [ "$WITHOUT_SYSZYDIS" = "0" ]; then
 USE_ZYDIS="0"
 USE_SYS_ZYDIS="0"
@@ -747,6 +765,8 @@ USE_SYS_ZYDIS="0"
 HAVE_PKGCFG_ZYDIS="0"
 ZYDIS_CFLAGS=""
 ZYDIS_LDFLAGS=""; fi
+if [ "$WANT_SYS_ZYDIS" = "1" ]; then
+case "$USE_SYS_ZYDIS" in 0|"") echo ; echo "ERROR: system zydis was requested but not found" >&2 ; echo ; exit 1 ;; esac; fi
 if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
 printf 'checking pkg-config flags for libsqsh... '
 tmp=`${PKGCONFIG} --cflags libsqsh 2>/dev/null`
