Release 2.1.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.2
+# This script was automatically generated by ACR v1.3
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -116,12 +116,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='radare2' ; VERSION='2.1.0-git' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
+ PKGNAME='radare2' ; VERSION='2.1.0' ; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
 
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-2.1.0-git to adapt to many kinds of systems.
+'configure' configures radare2-2.1.0 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -172,11 +172,11 @@ Optional Features:
   --without-gpl          do not build GPL code (grub, cxx, ... )
   --with-openssl         build with openssl if possible
   --with-rpath           use rpath to build
-  --with-compiler        Define compiler to use (see mk/)  (USERCC=gcc)
-  --with-ostype          Choose OS type ( gnulinux windows darwin haiku )  (USEROSTYPE=auto)
+  --with-compiler        Define compiler to use (see mk/) (USERCC=gcc)
+  --with-ostype          Choose OS type ( gnulinux windows darwin haiku ) (USEROSTYPE=auto)
   --without-pic          do not build libr as a program independent location
   --with-nonpic          build the library archives .a
-  --with-libversion      specify different libversion  (LIBVERSION=xxx)
+  --with-libversion      specify different libversion (LIBVERSION=xxx)
   --without-jemalloc     build without jemalloc
 "
 printf "
@@ -204,7 +204,7 @@ take_environ() {
 }
 
 show_version() {
-echo "radare2-2.1.0-git configuration script done with acr v1.2.
+echo "radare2-2.1.0 configuration script done with acr v1.3.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -228,7 +228,7 @@ case $flag in
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   radare2"
-echo "VERSION:   2.1.0-git"
+echo "VERSION:   2.1.0"
 echo "LANGS:     c"
 echo "REQUIRED:  libdl"
 echo "OPTIONAL:  libmagic"
@@ -326,7 +326,7 @@ echo "checking for working directories... ${WODIS}"
 echo "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe"
 
-:
+
 COMPILER=CC
 printf "checking for c compiler... "
 HAVE_LANG_C=1
@@ -426,15 +426,16 @@ else
 USE_LIB_MAGIC="0"
 LIBMAGIC="-lr_magic"; fi
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for capstone... '
 tmp=`${PKGCONFIG} --cflags capstone 2>/dev/null`
-if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_CAPSTONE=0;
-else
-CAPSTONE_CFLAGS=$tmp;
+if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_CAPSTONE=0; 
+else 
+CAPSTONE_CFLAGS=$tmp; 
 tmp=`${PKGCONFIG} --libs capstone 2>/dev/null`
-if [ $? = 0 ]; then
-echo yes; HAVE_PKGCFG_CAPSTONE=1;
+if [ $? = 0 ]; then 
+echo yes; HAVE_PKGCFG_CAPSTONE=1; 
 CAPSTONE_LDFLAGS=$tmp; fi; fi
 if [ 11 = "$WITH_CAPSTONE$HAVE_PKGCFG_CAPSTONE" ]; then
 
@@ -454,19 +455,17 @@ LIBZIP="-lrz"; fi
 else
 USE_LIB_ZIP="0"
 LIBZIP="-lrz"; fi
-
 HAVE_LIB_GMP="0"
 check_library HAVE_LIB_SSL ssl 0
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for openssl... '
 tmp=`${PKGCONFIG} --cflags openssl 2>/dev/null`
-if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_OPENSSL=0;
-else
-SSL_CFLAGS=$tmp;
+if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_OPENSSL=0; 
+else 
+SSL_CFLAGS=$tmp; 
 tmp=`${PKGCONFIG} --libs openssl 2>/dev/null`
-if [ $? = 0 ]; then
-echo yes; HAVE_PKGCFG_OPENSSL=1;
+if [ $? = 0 ]; then 
+echo yes; HAVE_PKGCFG_OPENSSL=1; 
 SSL_LDFLAGS=$tmp; fi; fi
 if [ ! "$SSL_LDFLAGS" = "" ]; then
 HAVE_OPENSSL="1"; fi
