Update SPP to fix the HAVE_SYSTEM warning

diff --git a/shlr/spp/configure b/shlr/spp/configure
--- a/shlr/spp/configure
+++ b/shlr/spp/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.9.0
+# This script was automatically generated by ACR v2.0.0
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -41,6 +41,11 @@ shift
 done
 }
 
+QUIET=0
+be_quiet() {
+	QUIET=1
+}
+
 VPATH=`dirname ${0}`
 if [ "${VPATH}" = "." ]; then
 	WODIS=current
@@ -78,6 +83,7 @@ CROSSBUILD=0
 BUILD=`guess_os`
 HOST="${BUILD}"
 TARGET="${HOST}"
+ETCDIR="/etc"
 SYSCONFDIR=""
 
 create_environ() {
@@ -85,7 +91,7 @@ create_environ() {
 : ${SPREFIX:="${PREFIX}"}
 : ${BINDIR:="${SPREFIX}/bin"}
 : ${SBINDIR:="${PREFIX}/sbin"}
-: ${SYSCONFDIR:="${SPREFIX}/etc"}
+: ${ETCDIR:="${SPREFIX}/etc"}
 : ${LIBDIR:="${SPREFIX}/lib"}
 : ${LIBEXECDIR:="${SPREFIX}/libexec"}
 : ${INCLUDEDIR:="${SPREFIX}/include"}
@@ -105,12 +111,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='spp' ; VERSION='1.2.0' ; VERSION_MAJOR=1; VERSION_MINOR=2; VERSION_PATCH=0; VERSION_NUMBER=10200; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
+ PKGNAME='spp' ; VERSION='1.3.0' ; VERSION_MAJOR=1; VERSION_MINOR=3; VERSION_PATCH=0; VERSION_NUMBER=10300; CONTACT_MAIL="pancake@nopcode.org" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nopcode.org>" ;
 }
 
 show_usage() {
 cat <<EOF2
-'configure' configures spp-1.2.0 to adapt to many kinds of systems.
+'configure' configures spp-1.3.0 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -122,6 +128,7 @@ Defaults for the options are specified in brackets.
 Configuration:
   -h, --help              display this help and exit
   -r, --report            show what libs/programs require to work
+  -q, --quiet             be quiet, less verbose (see ./configure -qV)
   -V, --version           display version information and exit
 
 Installation directories:
@@ -141,6 +148,7 @@ Fine tuning of the installation directories:
   --localstatedir=DIR    modifiable single-machine data [PREFIX/var]
   --mandir=DIR           man documentation [DATADIR/man]
   --sbindir=DIR          system admin executables [EPREFIX/sbin]
+  --etcdir=DIR           same as --sysconfdir (/etc)
   --sysconfdir=DIR       read-only single-machine data [PREFIX/etc]
   --sharedstatedir=DIR   modifiable architecture-independent data [PREFIX/com]
 
@@ -166,8 +174,22 @@ take_environ() {
 : ${PREFIX:=/usr/local/}
 }
 
+ochof() {
+	[ "$QUIET" = 1 ] && return
+	printf "$*"
+}
+
+ocho() {
+	[ "$QUIET" = 1 ] && return
+	echo "$*"
+}
+
 show_version() {
-echo "spp-1.2.0 configuration script done with acr v1.9.0.
+if [ "$QUIET" = 1 ]; then
+	echo "1.3.0"
+	exit 0
+fi
+echo "spp-1.3.0 configuration script done with acr v2.0.0.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -187,11 +209,16 @@ fi
 case $flag in
 -h|--help|--hel|--h|--he|-help)
 	show_usage ; ;;
+-qV|-quiet-version|--quiet-version)
+	be_quiet
+	show_version ; ;;
+-q|-quiet|--quiet)
+	be_quiet ; ;;
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   spp"
-echo "VERSION:   1.2.0"
+echo "VERSION:   1.3.0"
 echo "PKG-CONFIG:  r_util"
 echo "FLAGS:     --without-fork --enable-r2"
 	exit 0
@@ -223,7 +250,11 @@ echo "FLAGS:     --without-fork --enable-r2"
 --datadir)
 	DATADIR="$value"; ;;
 --sysconfdir)
-	SYSCONFDIR="$value"; ;;
+	SYSCONFDIR="$value"
+	ETCDIR="$value"; ;;
+--etcdir)
+	SYSCONFDIR="$value"
+	ETCDIR="$value"; ;;
 --sharedstatedir)
 	SHAREDSTATEDIR="$value"; ;;
 --localstatedir)
@@ -258,23 +289,49 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL HAVE_FORK WANT_R2 HAVE_PKGCONFIG PKGCONFIG R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_UTIL USE_R2"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL PKGCONFIG HAVE_FORK WANT_R2 HAVE_PKGCONFIG R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_UTIL USE_R2"
 
 create_environ
 
-echo "checking build system type... ${BUILD}"
-echo "checking host system type... ${HOST}"
-echo "checking target system type... ${TARGET}"
+ocho "checking build system type... ${BUILD}"
+ocho "checking host system type... ${HOST}"
+ocho "checking target system type... ${TARGET}"
 [ "${CROSSBUILD}" = 1 ] && echo "using crosscompilation mode."
 
 #split_host BUILD HOST TARGET
 [ -n "${prefix}" ] && PREFIX="${prefix}"
-echo "checking for working directories... ${WODIS}"
-echo "using prefix '${PREFIX}'"
+ocho "checking for working directories... ${WODIS}"
+ocho "using prefix '${PREFIX}'"
 ACR_RMFILES=""
 
 
-printf "checking for pkg-config... "
+ochof "checking for pkg-config... "
+if [ -n "$PKGCONFIG" ]; then
+	if [ -x "$PKGCONFIG" ]; then
+		_HAVE_PKGCONFIG="${PKGCONFIG}"
+	else
+		ocho "PKGCONFIG env is not executable"
+		PKGCONFIG=""
+	fi
+else
+	IFS=:
+	for A in ${PATH} ; do
+		if [ -x "${A}/pkg-config" ]; then
+			PKGCONFIG="${A}/pkg-config"
+		elif [ -x "${A}/pkgconf" ]; then
+			PKGCONFIG="${A}/pkgconf"
+		else
+			continue
+		fi
+		break
+	done
+	unset IFS
+fi
+if [ -n "${PKGCONFIG}" ]; then
+	ocho ${PKGCONFIG}
+else
+ocho no; fi
+ochof "checking for pkg-config... "
 if [ -x "${PKGCONFIG}" ]; then
 	FIND=${PKGCONFIG}
 else
@@ -289,15 +346,19 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_PKGCONFIG=1
 	PKGCONFIG=${FIND}
 else
 	HAVE_PKGCONFIG=0
 	PKGCONFIG=pkg-config
-echo no ; fi
-[ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
+if [ "" = 1 ]; then
+echo "Cannot find pkg-config" >&2
+else
+echo no
+fi ; fi
+if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find valid PKGCONFIG, pkg-config or pkgconf in PATH"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_util... '
 tmp=`${PKGCONFIG} --cflags r_util 2>/dev/null`
@@ -339,8 +400,8 @@ if [ -f "${VPATH}/${A}.acr" ]; then
    exit 1
   fi
  fi
- echo "creating ${SD_TARGET}"
-mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
+ ocho "creating ${SD_TARGET}"
+[ "${VPATH}" != '.' ] &&  mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
  cat ${VPATH}/${SD_TARGET}.acr | \
 eval sed -e "s,@VPATH@,${VPATH}/${A},g" ${SEDFLAGS} > ${SD_TARGET}.tmp
 
@@ -358,10 +419,12 @@ done
  if [ ! $? = 0 ]; then echo Cannot write target file ; control_c ; fi
 done
 
+if [ "$QUIET" = 0 ]; then
 echo
 echo "Final report:"
-for A in  HAVE_FORK USE_R2 PREFIX ; do # REPORT
+for A in  HAVE_FORK USE_R2 PREFIX ; do
 eval VAL="\$${A}"
-[ -z "${VAL}" ] && VAL="(null)"
+[ -z "${VAL}" ] && VAL="\"\""
 echo " - ${A} = ${VAL}"
 done
+fi
