removing path in redirection

diff --git a/binr/r2pm/r2pm b/binr/r2pm/r2pm
--- a/binr/r2pm/r2pm
+++ b/binr/r2pm/r2pm
@@ -125,7 +125,7 @@ mkdir -p "${R2PM_PLUGDIR}"
 
 R2PM_SYSPKG() {
 	IS_SYSPKG="$1"
-	echo "R2PM_SYSPKG is going to be deprecated" > /dev/stderr
+	echo "R2PM_SYSPKG is going to be deprecated" >&2
 }
 
 R2PM_DESC() {
@@ -231,12 +231,12 @@ R2PM_Info() {
 	if [ -n "${R2PM_DBDIR}" -a -d "${R2PM_DBDIR}" ]; then
 		echo "# Repository Database:"
 		cd "${R2PM_DBDIR}"
-		echo "# $(ls |wc -l) Packages" > /dev/stderr
+		echo "# $(ls |wc -l) Packages" >&2
 	fi
 	cd "${R2PM_USRDIR}/pkg"
 	echo "# Installed:"
-	printf "# $(ls |wc -l) Packages\n#  " > /dev/stderr
-	du -hs "${HOME}/.config/radare2" > /dev/stderr
+	printf "# $(ls |wc -l) Packages\n#  " >&2
+	du -hs "${HOME}/.config/radare2" >&2
 }
 
 R2PM_REGISTER() {
@@ -312,8 +312,8 @@ r2pm_uninstall() {
 				echo Oops
 			fi
 		else
-			echo "Unable to find package template for $2." > /dev/stderr
-			echo "Use -uu to remove it from the database." > /dev/stderr
+			echo "Unable to find package template for $2." >&2
+			echo "Use -uu to remove it from the database." >&2
 		fi
 	fi
 }
@@ -340,7 +340,7 @@ case "$1" in
 		TRAVIS_JOB=`${CURL} -s https://api.travis-ci.org/repos?slug=radare%2Fradare2| jq .[0].last_build_id`
 		TRAVIS_JOB=$(($TRAVIS_JOB+1))
 	fi
-	echo $TRAVIS_JOB > /dev/stderr
+	echo $TRAVIS_JOB >&2
 	# storage
 	${CURL} -s https://s3.amazonaws.com/archive.travis-ci.org/jobs/${TRAVIS_JOB}/log.txt |\
 		grep -C 1 ${TRAVIS_TYPE} | grep '\[ ' | sed -e 's,\[  \],['${TRAVIS_TYPE}'],g'
diff --git a/configure-plugins b/configure-plugins
--- a/configure-plugins
+++ b/configure-plugins
@@ -211,7 +211,7 @@ sort_vars
 
 if [ - != "${RMSTATIC}" ]; then
   if [ -z "${RMSTATIC}" ]; then
-    echo "Missing argument" > /dev/stderr
+    echo "Missing argument" >&2
     exit
   fi
   if [ -d "${RMSTATIC}" ]; then
