Allow multiple packages as arguments for r2pm -i,-c,-ci ##general

diff --git a/binr/r2pm/r2pm b/binr/r2pm/r2pm
--- a/binr/r2pm/r2pm
+++ b/binr/r2pm/r2pm
@@ -467,7 +467,11 @@ case "$1" in
 			fi
 		done
 	else
-		r2pm_install "$@"
+		A1="$1"
+		while [ -n "$2" ] ; do
+			r2pm_install $A1 "$2"
+			shift
+		done
 	fi
 	;;
 -uu)
@@ -542,25 +546,31 @@ case "$1" in
 	;;
 -c|clean)
 	if [ -n "$2" ]; then
-		FILE="$(pkgFilePath "$2")"
-		if [ -f "${FILE}" ]; then
-			NAME="$2"
-			ACTION=clean
-			export PATH="${R2PM_HOMEBINDIR}:${PATH}"
-			. "${FILE}"
-			echo $FILE TGZ=$R2PM_TGZ
-		else
-			echo "Cannot find $FILE"
-			exit 1
-		fi
+		RC=0
+		while [ -n "$2" ]; do
+			echo "Cleaning $2..."
+			FILE="$(pkgFilePath "$2")"
+			if [ -f "${FILE}" ]; then
+				NAME="$2"
+				ACTION=clean
+				export PATH="${R2PM_HOMEBINDIR}:${PATH}"
+				. "${FILE}"
+				echo $FILE TGZ=$R2PM_TGZ
+			else
+				echo "Cannot find $FILE"
+				RC=1
+			fi
 
-		if [ -d "${R2PM_GITDIR}/$2" ]; then
-			echo "Cleaning up ${R2PM_GITDIR}/$2..."
-			rm -rf "${R2PM_GITDIR}/$2"
-		else
-			echo "Cannot find $2 in ${R2PM_GITDIR}"
-			exit 1
-		fi
+			if [ -d "${R2PM_GITDIR}/$2" ]; then
+				echo "Cleaning up ${R2PM_GITDIR}/$2..."
+				rm -rf "${R2PM_GITDIR}/$2"
+			else
+				echo "Cannot find $2 in ${R2PM_GITDIR}"
+				RC=1
+			fi
+			shift
+		done
+		exit $RC
 	else
 		R2PM_List radare2 | grep radare2
 		if [ $? != 0 ]; then
