Send info/error messages to stderr

diff --git a/binr/r2pm/r2pm b/binr/r2pm/r2pm
--- a/binr/r2pm/r2pm
+++ b/binr/r2pm/r2pm
@@ -568,7 +568,7 @@ case "$1" in
 	if [ -n "$2" ]; then
 		RC=0
 		while [ -n "$2" ]; do
-			echo "Cleaning $2..."
+			echo "Cleaning $2..." >&2
 			FILE="$(pkgFilePath "$2")"
 			if [ -f "${FILE}" ]; then
 				NAME="$2"
@@ -577,15 +577,15 @@ case "$1" in
 				. "${FILE}"
 				echo $FILE TGZ=$R2PM_TGZ
 			else
-				echo "Cannot find $FILE"
+				echo "Cannot find $FILE" >&2
 				RC=1
 			fi
 
 			if [ -d "${R2PM_GITDIR}/$2" ]; then
-				echo "Cleaning up ${R2PM_GITDIR}/$2..."
+				echo "Cleaning up ${R2PM_GITDIR}/$2..." >&2
 				rm -rf "${R2PM_GITDIR}/$2"
 			else
-				echo "Cannot find $2 in ${R2PM_GITDIR}"
+				echo "Cannot find $2 in ${R2PM_GITDIR}" >&2
 				RC=1
 			fi
 			shift
